# Generated by Django 5.0 on 2023-12-26 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_category_id_alter_problem_id_alter_solution_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='not_agree',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
