# Generated by Django 5.0 on 2023-12-29 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_userprofile_profile_picture'),
        ('main', '0007_alter_comment_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Problem',
            new_name='Question',
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='solution',
            options={'ordering': ['-created_at']},
        ),
    ]
