# Generated by Django 5.0 on 2023-12-30 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_rename_problem_question_alter_comment_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='is_agree',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='not_agree',
        ),
        migrations.AddField(
            model_name='vote',
            name='value',
            field=models.IntegerField(default=0),
        ),
    ]
