# Generated by Django 5.0 on 2023-12-30 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_remove_solution_votes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solution',
            old_name='problem',
            new_name='question',
        ),
    ]
