# Generated by Django 5.0 on 2023-12-26 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_customuser_id_alter_userprofile_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(default='default_profile_pic.png', upload_to='profile_pics/'),
        ),
    ]
