# Generated by Django 5.0 on 2023-12-29 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_userprofile_total_point'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(default='1.png', upload_to='media/profile_pics/'),
        ),
    ]
