# Generated by Django 5.0 on 2023-12-27 11:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0005_alter_userprofile_profile_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('point', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('earn_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points', to='account.userprofile')),
            ],
        ),
    ]
