# Generated by Django 5.0 on 2023-12-27 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='point',
            name='action',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
